# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d86a2a71e01d3700d774e44e9afcaff8610fc7063d923008107cd7ab208db649f38972a5ce67c14c3a50f6fb2a98258c62721f4b2e5b735190597af77cff3b34

test:
  secret_key_base: d81f8be5f1f23b506f33dba1d8690595f47b5e94f1bf26647ad2a58cd146a4d450e29633b08bf554152d108fe1e7e5221417a3c00d65ebbaf38cdaf2d7df2b10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
